language: python

python:
  - "2.6"

# command to install dependencies
install:
  - pip install -r requirements.pip --use-mirrors

before_script:
  - psql -c 'create database edtrac_test;' -U postgres
  - ls

# command to run tests
script:
  - cd edtrac/edtrac_project
  - python manage.py test education.test